// Code generated by go-swagger; DO NOT EDIT.

package main

import (
	"log"
	"os"

	"mangapplizer-backend/restapi"
	"mangapplizer-backend/restapi/operations"

	// "mangapplizer-backend/restapi/operations/v1"
	"mangapplizer-backend/pkg/database"

	loads "github.com/go-openapi/loads"
	flags "github.com/jessevdk/go-flags"
)

// This file was generated by the swagger tool.
// Make sure not to overwrite this file after you generated it because all your edits would be lost!

func main() {

	swaggerSpec, err := loads.Embedded(restapi.SwaggerJSON, restapi.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	database.Initialize()
	db := database.GetDB()
	api := operations.NewMangapplizerAPI(swaggerSpec)
	server := restapi.NewServer(api)
	defer server.Shutdown()
	defer db.Close()

	parser := flags.NewParser(server, flags.Default)
	parser.ShortDescription = "Mangapplizer Monolith API"
	parser.LongDescription = "This application contains very limited amount of the API end points to improve our\ndevelopment life cycle. This application' future is not bright yet.\n"

	server.ConfigureFlags()
	for _, optsGroup := range api.CommandLineOptionsGroups {
		_, err := parser.AddGroup(optsGroup.ShortDescription, optsGroup.LongDescription, optsGroup.Options)
		if err != nil {
			log.Fatalln(err)
		}
	}

	if _, err := parser.Parse(); err != nil {
		code := 1
		if fe, ok := err.(*flags.Error); ok {
			if fe.Type == flags.ErrHelp {
				code = 0
			}
		}
		os.Exit(code)
	}

	server.ConfigureAPI()

	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}

}
