// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Mangapplizer Monolith API
This application contains very limited amount of the API end points to improve our
development life cycle. This application' future is not bright yet.



    Schemes:
      http
      https
    Host: 0.0.0.0:9092
    BasePath: /api
    Version: 0.1.0

    Consumes:
    - application/vnd.mangapplizer.api.v1+json

    Produces:
    - application/vnd.mangapplizer.api.v1+json

swagger:meta
*/
package restapi
