// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMangaParams creates a new GetMangaParams object
// no default values defined in spec.
func NewGetMangaParams() GetMangaParams {

	return GetMangaParams{}
}

// GetMangaParams contains all the bound params for the get manga operation
// typically these are obtained from a http.Request
//
// swagger:parameters getManga
type GetMangaParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Name of the searched manga
	  Required: true
	  In: path
	*/
	Manga string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetMangaParams() beforehand.
func (o *GetMangaParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rManga, rhkManga, _ := route.Params.GetOK("manga")
	if err := o.bindManga(rManga, rhkManga, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindManga binds and validates parameter Manga from path.
func (o *GetMangaParams) bindManga(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Manga = raw

	return nil
}
