// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "mangapplizer-backend/models"
)

// GetMangaOKCode is the HTTP code returned for type GetMangaOK
const GetMangaOKCode int = 200

/*GetMangaOK Successfull response

swagger:response getMangaOK
*/
type GetMangaOK struct {

	/*
	  In: Body
	*/
	Payload []*models.MangaList `json:"body,omitempty"`
}

// NewGetMangaOK creates GetMangaOK with default headers values
func NewGetMangaOK() *GetMangaOK {

	return &GetMangaOK{}
}

// WithPayload adds the payload to the get manga o k response
func (o *GetMangaOK) WithPayload(payload []*models.MangaList) *GetMangaOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get manga o k response
func (o *GetMangaOK) SetPayload(payload []*models.MangaList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMangaOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.MangaList, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetMangaUnauthorizedCode is the HTTP code returned for type GetMangaUnauthorized
const GetMangaUnauthorizedCode int = 401

/*GetMangaUnauthorized Authentication Error

swagger:response getMangaUnauthorized
*/
type GetMangaUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.AuthenticationError `json:"body,omitempty"`
}

// NewGetMangaUnauthorized creates GetMangaUnauthorized with default headers values
func NewGetMangaUnauthorized() *GetMangaUnauthorized {

	return &GetMangaUnauthorized{}
}

// WithPayload adds the payload to the get manga unauthorized response
func (o *GetMangaUnauthorized) WithPayload(payload *models.AuthenticationError) *GetMangaUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get manga unauthorized response
func (o *GetMangaUnauthorized) SetPayload(payload *models.AuthenticationError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMangaUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
