// Code generated by go-swagger; DO NOT EDIT.

package v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "mangapplizer-backend/models"
)

// GetMangaHandlerFunc turns a function with the right signature into a get manga handler
type GetMangaHandlerFunc func(GetMangaParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMangaHandlerFunc) Handle(params GetMangaParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetMangaHandler interface for that can handle valid get manga params
type GetMangaHandler interface {
	Handle(GetMangaParams, *models.Principal) middleware.Responder
}

// NewGetManga creates a new http.Handler for the get manga operation
func NewGetManga(ctx *middleware.Context, handler GetMangaHandler) *GetManga {
	return &GetManga{Context: ctx, Handler: handler}
}

/*GetManga swagger:route GET /v1/search/{manga} v1 search manga getManga

List of searched media

List of the searched manga

*/
type GetManga struct {
	Context *middleware.Context
	Handler GetMangaHandler
}

func (o *GetManga) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetMangaParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
